/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { healthOutputSchema } from "../../../../apps/backend/src/app.dto";
import { refreshTokenInputSchema, authTokenOutputSchema, exchangeCodeInputSchema } from "../../../../apps/backend/src/auth/auth.dto";
import { createUserFileUploadUrlInputSchema, presignedPutOutputSchema, createContentFileUploadUrlInputSchema, registerContentInputSchema, registerContentOutputSchema, updateContentMetadataInputSchema, updateContentMetadataOutputSchema, registerContentFileInputSchema, registerContentFileOutputSchema, removeContentFileInputSchema, removeContentFileOutputSchema, findContentInputSchema, findContentOutputSchema, getContentByIdInputSchema, getContentByIdOutputSchema, getContentStatisticInputSchema, getContentStatisticOutputSchema, getContentFileLinkInputSchema, getContentFileLinkOutputSchema, uploadTokenMetadataInputSchema, uploadTokenMetadataOutputSchema, requestLazyMintContentTokenInputSchema, requestLazyMintContentTokenOutputSchema, getContentConfigOutputSchema } from "../../../../apps/backend/src/content/content.dto";
import { findBlockedLicensesInputSchema, findBlockedLicensesOutputSchema } from "../../../../apps/backend/src/license/../common/license/blocked-license/blocked-license.dto";
import { findNotificationsInputSchema, findNotificationsOutputSchema, markNotificationAsReadInputSchema, markNotificationAsReadOutputSchema, markAllMyNotificationsAsReadOutputSchema } from "../../../../apps/backend/src/notification/notification.dto";
import { setPublisherInputSchema, setPublisherOutputSchema, getPublisherDataInputSchema, getPublisherDataOutputSchema, findPublishersInputSchema, findPublishersOutputSchema, mintContentNftTokenInputSchema, mintContentNftTokenOutputSchema } from "../../../../apps/backend/src/publisher/publisher.dto";

const appRouter = t.router({
  app: t.router({
    health: publicProcedure
      .output(healthOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    authTokenPayload: publicProcedure
      .output(z.any())
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    isClientAdmin: publicProcedure
      .output(z.boolean())
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  auth: t.router({
    refreshToken: publicProcedure
      .input(refreshTokenInputSchema)
      .output(authTokenOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    exchangeCode: publicProcedure
      .input(exchangeCodeInputSchema)
      .output(authTokenOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  contents: t.router({
    createUserFileUploadUrl: publicProcedure
      .input(createUserFileUploadUrlInputSchema)
      .output(presignedPutOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createContentFileUploadUrl: publicProcedure
      .input(createContentFileUploadUrlInputSchema)
      .output(presignedPutOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    registerContent: publicProcedure
      .input(registerContentInputSchema)
      .output(registerContentOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updateContentMetadata: publicProcedure
      .input(updateContentMetadataInputSchema)
      .output(updateContentMetadataOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    registerContentFile: publicProcedure
      .input(registerContentFileInputSchema)
      .output(registerContentFileOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    removeContentFile: publicProcedure
      .input(removeContentFileInputSchema)
      .output(removeContentFileOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findContent: publicProcedure
      .input(findContentInputSchema)
      .output(findContentOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getContentById: publicProcedure
      .input(getContentByIdInputSchema)
      .output(getContentByIdOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getContentStatistic: publicProcedure
      .input(getContentStatisticInputSchema)
      .output(getContentStatisticOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getContentFileLink: publicProcedure
      .input(getContentFileLinkInputSchema)
      .output(getContentFileLinkOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    uploadTokenMetadata: publicProcedure
      .input(uploadTokenMetadataInputSchema)
      .output(uploadTokenMetadataOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    requestLazyMintContentToken: publicProcedure
      .input(requestLazyMintContentTokenInputSchema)
      .output(requestLazyMintContentTokenOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    config: publicProcedure
      .output(getContentConfigOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  licenses: t.router({
    findBlockedLicenses: publicProcedure
      .input(findBlockedLicensesInputSchema)
      .output(findBlockedLicensesOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  notifications: t.router({
    onMessage: publicProcedure
      .subscription(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findMyNotifications: publicProcedure
      .input(findNotificationsInputSchema)
      .output(findNotificationsOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    markMyNotificationAsRead: publicProcedure
      .input(markNotificationAsReadInputSchema)
      .output(markNotificationAsReadOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    markAllMyNotificationsAsRead: publicProcedure
      .output(markAllMyNotificationsAsReadOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  publishers: t.router({
    setPublisher: publicProcedure
      .input(setPublisherInputSchema)
      .output(setPublisherOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getPublisher: publicProcedure
      .input(getPublisherDataInputSchema)
      .output(getPublisherDataOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findPublishers: publicProcedure
      .input(findPublishersInputSchema)
      .output(findPublishersOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    mintContentNftToken: publicProcedure
      .input(mintContentNftTokenInputSchema)
      .output(mintContentNftTokenOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
