/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { healthOutputSchema } from "../../../../apps/backend/src/app.dto";
import { refreshTokenInputSchema, authTokenOutputSchema, exchangeCodeInputSchema } from "../../../../apps/backend/src/auth/auth.dto";
import { createUserFileUploadUrlInputSchema, createContentUploadUrlOutputSchema, createContentUploadUrlInputSchema, registerContentInputSchema, registerContentOutputSchema, findContentInputSchema, findContentOutputSchema, getContentLinkInputSchema, getContentLinkOutputSchema, uploadMetadataInputSchema, uploadMetadataOutputSchema } from "../../../../apps/backend/src/file/file.dto";
import { findBlockedLicensesInputSchema, findBlockedLicensesOutputSchema } from "../../../../apps/backend/src/license/../common/license/blocked-license/blocked-license.dto";
import { setPublisherInputSchema, setPublisherOutputSchema, getPublisherDataInputSchema, getPublisherDataOutputSchema, findPublishersInputSchema, findPublishersOutputSchema, mintContentNftTokenInputSchema, mintContentNftTokenOutputSchema } from "../../../../apps/backend/src/publisher/publisher.dto";

const appRouter = t.router({
  app: t.router({
    health: publicProcedure
      .output(healthOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    authTokenPayload: publicProcedure
      .output(z.any())
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    isClientAdmin: publicProcedure
      .output(z.boolean())
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  auth: t.router({
    refreshToken: publicProcedure
      .input(refreshTokenInputSchema)
      .output(authTokenOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    exchangeCode: publicProcedure
      .input(exchangeCodeInputSchema)
      .output(authTokenOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  files: t.router({
    createUserFileUploadUrl: publicProcedure
      .input(createUserFileUploadUrlInputSchema)
      .output(createContentUploadUrlOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createContentUploadUrl: publicProcedure
      .input(createContentUploadUrlInputSchema)
      .output(createContentUploadUrlOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    registerContent: publicProcedure
      .input(registerContentInputSchema)
      .output(registerContentOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findContent: publicProcedure
      .input(findContentInputSchema)
      .output(findContentOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getContentLink: publicProcedure
      .input(getContentLinkInputSchema)
      .output(getContentLinkOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    uploadMetadata: publicProcedure
      .input(uploadMetadataInputSchema)
      .output(uploadMetadataOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  licenses: t.router({
    findBlockedLicenses: publicProcedure
      .input(findBlockedLicensesInputSchema)
      .output(findBlockedLicensesOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  publishers: t.router({
    setPublisher: publicProcedure
      .input(setPublisherInputSchema)
      .output(setPublisherOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getPublisher: publicProcedure
      .input(getPublisherDataInputSchema)
      .output(getPublisherDataOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findPublishers: publicProcedure
      .input(findPublishersInputSchema)
      .output(findPublishersOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    mintContentNftToken: publicProcedure
      .input(mintContentNftTokenInputSchema)
      .output(mintContentNftTokenOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
